# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CineTrack Pro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CineTrack Pro
    pod 'UnityAds'

end
